### ISSUE TITLE
openAI api key not free

### ISSUE THREAD

**Issue by aditya-8-88** [AbhimanyuSingh2005/Quizz-Craft#1]
why not shift to gemini or some other free api key provider

**Comment by AbhimanyuSingh2005** [comment]
I have already given code for both openAi and gemini. Its up to you which you want to use.
OpenAi gives more accurate result but it is paid and gemini is free but its response may have some error.

**Comment by aditya-8-88** [comment]
can you include the gemini setup in readme.md

**Comment by AbhimanyuSingh2005** [comment]
ok
